version: "3.7"

services:
  backend:
    build:
      context: ./backend
      args:
        project_directory: "/backend_projects/"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - "./backend:/backend_projects"
    links:
      - llid_flask
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: "flask run --host 0.0.0.0 --port 5000"

  llid_flask:
    build:
      context: ./llid
      args:
        project_directory: "/llid_projects/"
    ports:
      - "5001:5001"
    expose:
      - "5001"
    volumes:
      - "./llid:/llid_projects"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: "flask run --host 0.0.0.0 --port 5001"

  errant_flask:
    build:
      context: ./errant
      args:
        project_directory: "/errant_projects/"
    ports:
      - "5002:5002"
    expose:
      - "5002"
    volumes:
      - "./errant:/errant_projects"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: "flask run --host 0.0.0.0 --port 5002"


  front:
    build:
      context: ./frontend
      args:
        project_directory: "/frontend_projects/"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - backend
    volumes:
      - "./frontend:/frontend_projects"
      - "/frontend_projects/node_modules/"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: sh -c "cd /frontend_projects/app  && yarn start"